---
dependencies:
  - name: ui
    version: 1.0.0
    repository: https://github.com/czm41k/ui.git

  - name: post
    version: 1.0.0
    repository: https://github.com/czm41k/post.git

  - name: comment
    version: 1.0.0
    repository: https://github.com/czm41k/comment.git

  - name: mongodb
    version: 0.4.18
    repository: https://kubernetes-charts.storage.googleapis.com
...
