---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: reddit-demo
  namespace: demo-flux
  annotations:
    # flux.weave.works/tag.chart-image: semver:~0.1
    fluxcd.io/tag.comment: semver:~0.1
    fluxcd.io/tag.post: semver:~0.1
    fluxcd.io/tag.ui: semver:~0.1
    fluxcd.io/automated: 'true'
spec:
  releaseName: reddit-demo
  chart:
    git: git@github.com:czm41k/reddit-flux
    path: charts/reddit
    ref: master
  values:
    ui:
      image:
        repository: czm41k/ui
        tag: 0.1.3
    post:
      image:
        repository: czm41k/post
        tag: 0.1.1
    comment:
      image:
        repository: czm41k/comment
        tag: 0.1.1
